var base_url = "https://as88kbu9j5.execute-api.us-east-1.amazonaws.com/final/";

var login_url = base_url + "login";   // POST
var regist_url = base_url + "regist"; // POST
var getClassificationsHierarychy_url = base_url + "getClassificationsHierarchy"; //GET
var addClassification_url = base_url + "addClassification"; //POST
var addAlgorithm_url = base_url + "addAlgorithm"; //POST
var uploadImplementation_url = base_url + "uploadImplementation"; //POST
var getImplementation_url = base_url + "getImplementation"; //POST
var uploadProblemInstance_url = base_url + "uploadProblemInstance"; //POST
var getProblemInstance_url = base_url + "getProblemInstance"; // POST
var uploadBenchmark_url = base_url + "uploadBenchmark"; //POST
var deleteBenchmrk_url = base_url + "deleteBenchmark"; //POST
var deleteProblemInstance_url = base_url + "deleteProblemInstance"; //POST
var deleteImplementation_url = base_url + "deleteImplementation"; // POST
var deleteAlgorithm_url = base_url + "deleteAlgorithm"; // POST
var reclassifyAlgorithm_url = base_url + "reclassifyAlgorithm"; //POST
var mergeSibilingClassification_url = base_url + "mergeSibilingClassification"; //POST
var deleteClassification_url = base_url + "deleteClassification"; // POST
var getRegisteredUsers_url = base_url + "getRegisteredUsers"; //GET
var deleteRegisteredUser_url = base_url + "deleteRegisteredUser"; //POST
var uploadActivity_url = base_url + "uploadActivity"; //POST
var getActivities_url = base_url + "getActivitiesForUser"; //POST